from enum import Enum
class Env(Enum):
    MONGO_URL = "MONGO_URL"
    DATABASE = "DATABASE"
    #! DO NOT MODIFY THE ENUM VALUES, THEY ARE FOLDER NAMES IN THE BUCKET
    INDEPENDENCE_DAY = "INDEPENDENCE_DAY"
    TEACHERS_DAY = "TEACHERS_DAY"
    CHILDRENS_DAY = "CHILDRENS_DAY"
    CHRISTMAS_DAY = "X_MAS_DAY"
    PONGAL_DAY = "PONGAL_DAY"
    FETE_DAY = "FETE_DAY"
    SPORTS_DAY = "SPORTS_DAY"
    SCIENCE_EXPO = "SCIENCE_EXPO"